alter table varieties disable row level security;
alter table gradings disable row level security;
alter table cold_storages disable row level security;
alter table mandis disable row level security;
alter table parties disable row level security;
alter table purchases disable row level security;
alter table dispatches disable row level security;
alter table sales disable row level security;
alter table payments disable row level security;
